import { RocklawLocationNode } from './liveScene';

export type RocklawPlaceLayout = RocklawLocationNode;

export const ROCKLAW_MAP_LAYOUT: Record<string, RocklawPlaceLayout> = {
  elena_home: {
    id: 'elena_home',
    key: 'elena_home',
    label: 'Elena Home',
    type: 'residence',
    center: { x: 8, y: 10 },
    region: { x: 5, y: 7, width: 6, height: 5 },
    standingSlots: [{ x: 8, y: 10 }, { x: 7, y: 10 }, { x: 9, y: 10 }],
    sceneSlots: [{ x: 7, y: 10 }, { x: 9, y: 10 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x93a7b8,
    neighbors: ['forge', 'square'],
    spriteKey: 'house',
  },
  marcus_home: {
    id: 'marcus_home',
    key: 'marcus_home',
    label: 'Marcus Home',
    type: 'residence',
    center: { x: 24, y: 6 },
    region: { x: 21, y: 3, width: 6, height: 5 },
    standingSlots: [{ x: 24, y: 6 }, { x: 23, y: 6 }, { x: 25, y: 6 }],
    sceneSlots: [{ x: 23, y: 6 }, { x: 25, y: 6 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x8ea4c2,
    neighbors: ['market', 'square'],
    spriteKey: 'house',
  },
  sera_home: {
    id: 'sera_home',
    key: 'sera_home',
    label: 'Sera Home',
    type: 'residence',
    center: { x: 40, y: 10 },
    region: { x: 37, y: 7, width: 6, height: 5 },
    standingSlots: [{ x: 40, y: 10 }, { x: 39, y: 10 }, { x: 41, y: 10 }],
    sceneSlots: [{ x: 39, y: 10 }, { x: 41, y: 10 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xa6907e,
    neighbors: ['inn', 'market'],
    spriteKey: 'house',
  },
  lena_home: {
    id: 'lena_home',
    key: 'lena_home',
    label: 'Lena Home',
    type: 'residence',
    center: { x: 8, y: 38 },
    region: { x: 5, y: 35, width: 6, height: 5 },
    standingSlots: [{ x: 8, y: 38 }, { x: 7, y: 38 }, { x: 9, y: 38 }],
    sceneSlots: [{ x: 7, y: 38 }, { x: 9, y: 38 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x8da1cf,
    neighbors: ['shrine', 'square'],
    spriteKey: 'house',
  },
  finn_home: {
    id: 'finn_home',
    key: 'finn_home',
    label: 'Finn Home',
    type: 'residence',
    center: { x: 40, y: 38 },
    region: { x: 37, y: 35, width: 6, height: 5 },
    standingSlots: [{ x: 40, y: 38 }, { x: 39, y: 38 }, { x: 41, y: 38 }],
    sceneSlots: [{ x: 39, y: 38 }, { x: 41, y: 38 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x7fa476,
    neighbors: ['farm', 'warehouse'],
    spriteKey: 'house',
  },
  forge: {
    id: 'forge',
    key: 'forge',
    label: 'Forge',
    type: 'industry',
    center: { x: 16, y: 16 },
    region: { x: 12, y: 13, width: 8, height: 6 },
    standingSlots: [{ x: 16, y: 16 }, { x: 15, y: 16 }, { x: 17, y: 16 }, { x: 16, y: 17 }],
    sceneSlots: [{ x: 15, y: 16 }, { x: 17, y: 16 }, { x: 16, y: 17 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xc9804b,
    neighbors: ['market', 'square', 'elena_home'],
    spriteKey: 'forge',
  },
  market: {
    id: 'market',
    key: 'market',
    label: 'Market',
    type: 'trade',
    center: { x: 24, y: 16 },
    region: { x: 20, y: 13, width: 8, height: 6 },
    standingSlots: [{ x: 24, y: 16 }, { x: 23, y: 16 }, { x: 25, y: 16 }, { x: 24, y: 17 }, { x: 22, y: 16 }],
    sceneSlots: [{ x: 23, y: 16 }, { x: 25, y: 16 }, { x: 24, y: 17 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xe1b756,
    neighbors: ['square', 'inn', 'shrine', 'warehouse', 'forge', 'bakery', 'farm', 'marcus_home', 'sera_home'],
    spriteKey: 'market',
  },
  inn: {
    id: 'inn',
    key: 'inn',
    label: 'Inn',
    type: 'hospitality',
    center: { x: 32, y: 24 },
    region: { x: 28, y: 21, width: 8, height: 6 },
    standingSlots: [{ x: 32, y: 24 }, { x: 31, y: 24 }, { x: 33, y: 24 }, { x: 32, y: 25 }],
    sceneSlots: [{ x: 31, y: 24 }, { x: 33, y: 24 }, { x: 32, y: 25 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xb86e45,
    neighbors: ['square', 'market', 'shrine', 'warehouse', 'bakery', 'farm', 'sera_home'],
    spriteKey: 'inn',
  },
  farm: {
    id: 'farm',
    key: 'farm',
    label: 'Farm',
    type: 'agriculture',
    center: { x: 32, y: 32 },
    region: { x: 28, y: 29, width: 8, height: 7 },
    standingSlots: [{ x: 32, y: 32 }, { x: 31, y: 32 }, { x: 33, y: 32 }, { x: 32, y: 33 }],
    sceneSlots: [{ x: 31, y: 32 }, { x: 33, y: 32 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x7daf56,
    neighbors: ['market', 'inn', 'warehouse', 'bakery', 'mine', 'finn_home'],
    spriteKey: 'farm',
  },
  shrine: {
    id: 'shrine',
    key: 'shrine',
    label: 'Shrine',
    type: 'spiritual',
    center: { x: 16, y: 24 },
    region: { x: 12, y: 21, width: 8, height: 6 },
    standingSlots: [{ x: 16, y: 24 }, { x: 15, y: 24 }, { x: 17, y: 24 }, { x: 16, y: 25 }],
    sceneSlots: [{ x: 15, y: 24 }, { x: 17, y: 24 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x8d9fe8,
    neighbors: ['square', 'market', 'inn', 'warehouse', 'gate', 'mine', 'lena_home'],
    spriteKey: 'shrine',
  },
  gate: {
    id: 'gate',
    key: 'gate',
    label: 'Gate',
    type: 'civic',
    center: { x: 16, y: 32 },
    region: { x: 13, y: 30, width: 6, height: 5 },
    standingSlots: [{ x: 16, y: 32 }, { x: 15, y: 32 }, { x: 17, y: 32 }],
    sceneSlots: [{ x: 15, y: 32 }, { x: 17, y: 32 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x89b2c9,
    neighbors: ['shrine', 'square', 'mine'],
    spriteKey: 'gate',
  },
  square: {
    id: 'square',
    key: 'square',
    label: 'Square',
    type: 'civic',
    center: { x: 24, y: 24 },
    region: { x: 20, y: 21, width: 8, height: 6 },
    standingSlots: [{ x: 24, y: 24 }, { x: 23, y: 24 }, { x: 25, y: 24 }, { x: 24, y: 25 }],
    sceneSlots: [{ x: 23, y: 24 }, { x: 25, y: 24 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xc4ab85,
    neighbors: ['market', 'inn', 'shrine', 'warehouse', 'forge', 'gate', 'bakery', 'elena_home', 'marcus_home', 'lena_home'],
    spriteKey: 'square',
  },
  mine: {
    id: 'mine',
    key: 'mine',
    label: 'Mine',
    type: 'resource',
    center: { x: 24, y: 32 },
    region: { x: 21, y: 30, width: 7, height: 5 },
    standingSlots: [{ x: 24, y: 32 }, { x: 23, y: 32 }, { x: 25, y: 32 }],
    sceneSlots: [{ x: 23, y: 32 }, { x: 25, y: 32 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x7c7f8d,
    neighbors: ['gate', 'shrine', 'warehouse', 'farm'],
    spriteKey: 'mine',
  },
  bakery: {
    id: 'bakery',
    key: 'bakery',
    label: 'Bakery',
    type: 'trade',
    center: { x: 32, y: 16 },
    region: { x: 29, y: 14, width: 6, height: 5 },
    standingSlots: [{ x: 32, y: 16 }, { x: 31, y: 16 }, { x: 33, y: 16 }],
    sceneSlots: [{ x: 31, y: 16 }, { x: 33, y: 16 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xd59f4a,
    neighbors: ['inn', 'square', 'market', 'farm'],
    spriteKey: 'bakery',
  },
  warehouse: {
    id: 'warehouse',
    key: 'warehouse',
    label: 'Warehouse',
    type: 'logistics',
    center: { x: 24, y: 40 },
    region: { x: 21, y: 38, width: 7, height: 5 },
    standingSlots: [{ x: 24, y: 40 }, { x: 23, y: 40 }, { x: 25, y: 40 }, { x: 24, y: 41 }],
    sceneSlots: [{ x: 23, y: 40 }, { x: 25, y: 40 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x6aa4a1,
    neighbors: ['square', 'market', 'inn', 'shrine', 'farm', 'mine', 'finn_home'],
    spriteKey: 'warehouse',
  },
};

export function getPlaceLayout(placeName: string): RocklawPlaceLayout {
  return ROCKLAW_MAP_LAYOUT[placeName] ?? {
    id: placeName,
    key: placeName,
    label: placeName,
    type: 'civic',
    center: { x: 22, y: 13 },
    region: { x: 20, y: 11, width: 5, height: 5 },
    standingSlots: [{ x: 22, y: 13 }],
    sceneSlots: [{ x: 22, y: 13 }, { x: 23, y: 13 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xc4ab85,
    neighbors: ['square'],
    spriteKey: 'fallback',
  };
}

export const ROCKLAW_PLACE_LIST = Object.values(ROCKLAW_MAP_LAYOUT);

export type RocklawOverviewPrimaryLane = {
  source: string;
  target: string;
  sourceHandle: string;
  targetHandle: string;
};

export const ROCKLAW_OVERVIEW_PRIMARY_LANES: RocklawOverviewPrimaryLane[] = [
  { source: 'elena_home', target: 'forge', sourceHandle: 'bottom-center', targetHandle: 'top-left' },
  { source: 'forge', target: 'square', sourceHandle: 'right-center', targetHandle: 'left-top' },
  { source: 'marcus_home', target: 'market', sourceHandle: 'bottom-center', targetHandle: 'top-center' },
  { source: 'market', target: 'square', sourceHandle: 'bottom-center', targetHandle: 'top-center' },
  { source: 'sera_home', target: 'inn', sourceHandle: 'bottom-center', targetHandle: 'top-right' },
  { source: 'inn', target: 'square', sourceHandle: 'left-center', targetHandle: 'right-top' },
  { source: 'lena_home', target: 'shrine', sourceHandle: 'top-center', targetHandle: 'bottom-left' },
  { source: 'shrine', target: 'square', sourceHandle: 'right-center', targetHandle: 'left-center' },
  { source: 'finn_home', target: 'farm', sourceHandle: 'top-center', targetHandle: 'bottom-right' },
  { source: 'farm', target: 'warehouse', sourceHandle: 'left-center', targetHandle: 'right-center' },
  { source: 'warehouse', target: 'square', sourceHandle: 'left-top', targetHandle: 'right-center' },
  { source: 'shrine', target: 'gate', sourceHandle: 'left-bottom', targetHandle: 'right-center' },
  { source: 'warehouse', target: 'mine', sourceHandle: 'bottom-center', targetHandle: 'top-right' },
  { source: 'inn', target: 'bakery', sourceHandle: 'right-top', targetHandle: 'left-center' },
];

export function getPlaceGraph(): RocklawLocationNode[] {
  return ROCKLAW_PLACE_LIST;
}
