import { RocklawLocationNode } from './liveScene';

export type RocklawPlaceLayout = RocklawLocationNode;

export const ROCKLAW_MAP_LAYOUT: Record<string, RocklawPlaceLayout> = {
  forge: {
    id: 'forge',
    key: 'forge',
    label: 'Forge',
    type: 'industry',
    center: { x: 10, y: 8 },
    region: { x: 6, y: 5, width: 8, height: 6 },
    standingSlots: [{ x: 10, y: 8 }, { x: 9, y: 8 }, { x: 11, y: 8 }, { x: 10, y: 9 }],
    sceneSlots: [{ x: 9, y: 8 }, { x: 11, y: 8 }, { x: 10, y: 9 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xc9804b,
    neighbors: ['market'],
    spriteKey: 'forge',
  },
  market: {
    id: 'market',
    key: 'market',
    label: 'Market',
    type: 'trade',
    center: { x: 10, y: 18 },
    region: { x: 6, y: 15, width: 8, height: 6 },
    standingSlots: [{ x: 10, y: 18 }, { x: 9, y: 18 }, { x: 11, y: 18 }, { x: 10, y: 19 }, { x: 8, y: 18 }],
    sceneSlots: [{ x: 9, y: 18 }, { x: 11, y: 18 }, { x: 10, y: 19 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xe1b756,
    neighbors: ['forge', 'square', 'shrine'],
    spriteKey: 'market',
  },
  inn: {
    id: 'inn',
    key: 'inn',
    label: 'Inn',
    type: 'hospitality',
    center: { x: 38, y: 8 },
    region: { x: 34, y: 5, width: 8, height: 6 },
    standingSlots: [{ x: 38, y: 8 }, { x: 37, y: 8 }, { x: 39, y: 8 }, { x: 38, y: 9 }],
    sceneSlots: [{ x: 37, y: 8 }, { x: 39, y: 8 }, { x: 38, y: 9 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xb86e45,
    neighbors: ['bakery'],
    spriteKey: 'inn',
  },
  farm: {
    id: 'farm',
    key: 'farm',
    label: 'Farm',
    type: 'agriculture',
    center: { x: 38, y: 30 },
    region: { x: 34, y: 27, width: 8, height: 7 },
    standingSlots: [{ x: 38, y: 30 }, { x: 37, y: 30 }, { x: 39, y: 30 }, { x: 38, y: 31 }],
    sceneSlots: [{ x: 37, y: 30 }, { x: 39, y: 30 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x7daf56,
    neighbors: ['bakery', 'warehouse', 'mine'],
    spriteKey: 'farm',
  },
  shrine: {
    id: 'shrine',
    key: 'shrine',
    label: 'Shrine',
    type: 'spiritual',
    center: { x: 10, y: 42 },
    region: { x: 6, y: 39, width: 8, height: 6 },
    standingSlots: [{ x: 10, y: 42 }, { x: 9, y: 42 }, { x: 11, y: 42 }, { x: 10, y: 43 }],
    sceneSlots: [{ x: 9, y: 42 }, { x: 11, y: 42 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x8d9fe8,
    neighbors: ['market', 'gate'],
    spriteKey: 'shrine',
  },
  gate: {
    id: 'gate',
    key: 'gate',
    label: 'Gate',
    type: 'civic',
    center: { x: 24, y: 42 },
    region: { x: 21, y: 40, width: 6, height: 5 },
    standingSlots: [{ x: 24, y: 42 }, { x: 23, y: 42 }, { x: 25, y: 42 }],
    sceneSlots: [{ x: 23, y: 42 }, { x: 25, y: 42 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x89b2c9,
    neighbors: ['shrine', 'warehouse', 'mine'],
    spriteKey: 'gate',
  },
  square: {
    id: 'square',
    key: 'square',
    label: 'Square',
    type: 'civic',
    center: { x: 24, y: 18 },
    region: { x: 21, y: 16, width: 6, height: 5 },
    standingSlots: [{ x: 24, y: 18 }, { x: 23, y: 18 }, { x: 25, y: 18 }, { x: 24, y: 19 }],
    sceneSlots: [{ x: 23, y: 18 }, { x: 25, y: 18 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xc4ab85,
    neighbors: ['market', 'bakery', 'warehouse'],
    spriteKey: 'square',
  },
  mine: {
    id: 'mine',
    key: 'mine',
    label: 'Mine',
    type: 'resource',
    center: { x: 38, y: 42 },
    region: { x: 35, y: 40, width: 7, height: 5 },
    standingSlots: [{ x: 38, y: 42 }, { x: 37, y: 42 }, { x: 39, y: 42 }],
    sceneSlots: [{ x: 37, y: 42 }, { x: 39, y: 42 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x7c7f8d,
    neighbors: ['farm', 'gate'],
    spriteKey: 'mine',
  },
  bakery: {
    id: 'bakery',
    key: 'bakery',
    label: 'Bakery',
    type: 'trade',
    center: { x: 38, y: 18 },
    region: { x: 35, y: 16, width: 6, height: 5 },
    standingSlots: [{ x: 38, y: 18 }, { x: 37, y: 18 }, { x: 39, y: 18 }],
    sceneSlots: [{ x: 37, y: 18 }, { x: 39, y: 18 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xd59f4a,
    neighbors: ['inn', 'square', 'farm'],
    spriteKey: 'bakery',
  },
  warehouse: {
    id: 'warehouse',
    key: 'warehouse',
    label: 'Warehouse',
    type: 'logistics',
    center: { x: 24, y: 30 },
    region: { x: 21, y: 28, width: 7, height: 5 },
    standingSlots: [{ x: 24, y: 30 }, { x: 23, y: 30 }, { x: 25, y: 30 }, { x: 24, y: 31 }],
    sceneSlots: [{ x: 23, y: 30 }, { x: 25, y: 30 }],
    labelOffset: { x: 0, y: -2 },
    color: 0x6aa4a1,
    neighbors: ['square', 'farm', 'gate'],
    spriteKey: 'warehouse',
  },
};

export function getPlaceLayout(placeName: string): RocklawPlaceLayout {
  return ROCKLAW_MAP_LAYOUT[placeName] ?? {
    id: placeName,
    key: placeName,
    label: placeName,
    type: 'civic',
    center: { x: 22, y: 13 },
    region: { x: 20, y: 11, width: 5, height: 5 },
    standingSlots: [{ x: 22, y: 13 }],
    sceneSlots: [{ x: 22, y: 13 }, { x: 23, y: 13 }],
    labelOffset: { x: 0, y: -2 },
    color: 0xc4ab85,
    neighbors: ['square'],
    spriteKey: 'fallback',
  };
}

export const ROCKLAW_PLACE_LIST = Object.values(ROCKLAW_MAP_LAYOUT);

export function getPlaceGraph(): RocklawLocationNode[] {
  return ROCKLAW_PLACE_LIST;
}
