workspace_dir = "workspace"
default_provider = "openrouter"
default_model = "google/gemini-2.5-flash"
default_temperature = 0.8

[gateway]
port = 42619
host = "0.0.0.0"
require_pairing = false
allow_public_bind = true

[cost]
enabled = false
